### ISSUE TITLE
Add URL to Elm package in GH

### ISSUE THREAD

**Issue by kutyel** [lydell/elm-app-url#1]
Hey! Thanks for this package, it is a step in the right direction for routing in Elm IMHO 🙌🏻 

Just as in https://package.elm-lang.org/packages/lydell/elm-app-url/latest/ there is a way to navigate to GH, I think it would be nice that the URL for the package would also appear in the GH description, let me know what you think 😉

**Comment by lydell** [comment]
Good idea! Added.
